## what's the self-attention? 

In [1]:
import torch

In [16]:
batch = 4
dim = 32
length = 8

In [17]:
x = torch.randn(batch, length, dim) # batch, length, vector-dim

In [18]:
x[0].shape

torch.Size([8, 32])

In [19]:
x[0][0] # some word's initial representation

tensor([-0.2287, -0.1237, -0.0114,  1.5521, -1.0304,  0.9804,  0.1499, -0.6190,
         1.1966, -0.0468, -0.4214, -0.4172, -0.4895,  0.5500, -1.1692, -0.1066,
         0.1798, -0.1861, -1.7311, -0.5634, -0.9203,  0.4252,  1.1050, -0.0987,
        -0.2975, -0.0341, -0.0478,  1.7376, -1.1968, -0.8195, -0.7322,  1.7068])

In [21]:
tril = torch.tril(torch.ones(length, length))

In [22]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
weights = torch.zeros(length, length)

In [24]:
weights

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
weights = weights.masked_fill(tril == 0, float('-inf'))

In [26]:
weights

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
import torch.nn.functional as F

In [30]:
weights = F.softmax(weights, dim=1)

In [31]:
weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
print(weights.shape)
print(x.shape)

In [32]:
out = weights @ x

In [33]:
out

tensor([[[-2.2873e-01, -1.2372e-01, -1.1437e-02,  ..., -8.1952e-01,
          -7.3220e-01,  1.7068e+00],
         [ 3.1518e-01,  4.5397e-01,  3.6987e-01,  ..., -1.8477e-01,
           4.5158e-01,  4.2963e-01],
         [ 6.7803e-01,  2.7806e-01,  4.3219e-01,  ..., -6.0472e-01,
           4.8114e-02,  1.1949e-01],
         ...,
         [ 5.5755e-01,  7.1188e-01,  3.9822e-01,  ..., -3.5320e-01,
           1.4337e-03, -3.4887e-01],
         [ 3.1575e-01,  7.8707e-01,  2.5335e-01,  ..., -2.6284e-01,
          -1.3354e-01, -4.9160e-01],
         [ 3.1321e-01,  7.7063e-01,  7.2988e-02,  ..., -3.0235e-01,
          -1.2208e-01, -5.6847e-01]],

        [[ 3.2266e-01, -5.5382e-01, -3.3814e-01,  ..., -1.2027e+00,
          -7.4612e-01, -1.0881e+00],
         [-1.7338e-01,  6.1709e-01, -4.0853e-01,  ..., -5.3127e-01,
          -1.7906e-01, -2.4196e-01],
         [-1.4671e-01,  2.2366e-01,  7.4242e-02,  ...,  2.5735e-01,
          -2.2835e-01, -1.9535e-01],
         ...,
         [ 1.6050e-01, -2

## add some learnable components 

In [34]:
from torch import nn

In [37]:
head_size = 16
key = nn.Linear(dim, head_size, bias=False)
query = nn.Linear(dim, head_size, bias=False)

k = key(x)

In [38]:
k.size()

torch.Size([4, 8, 16])

In [39]:
q = query(x)

In [40]:
q.size()

torch.Size([4, 8, 16])

In [42]:
weights = q@k.transpose(1, 2)

In [43]:
weights.shape

torch.Size([4, 8, 8])

In [44]:
weights

tensor([[[-0.6622, -0.8045, -0.4547, -0.5178, -1.8640, -0.1153, -0.8735,
          -0.2420],
         [-0.4997, -0.7454,  0.1323, -0.1676, -2.2134, -3.3614, -1.5745,
           0.3952],
         [ 0.8349,  0.6129, -1.0411, -0.1623,  2.5310,  2.4834,  0.5778,
          -0.3231],
         [-0.1163,  0.2566, -0.9266, -0.4559,  1.3923,  0.4611,  0.2469,
          -0.6366],
         [ 0.5025,  0.0474, -2.5849,  0.0661,  0.6871, -3.0180,  2.0473,
           0.4873],
         [ 0.3404,  1.0072, -0.7737,  0.7192,  0.7938, -0.0130,  0.4553,
          -1.0714],
         [-1.0977, -1.9826, -0.8031,  0.3475, -1.5062, -2.5116, -0.3329,
           1.3282],
         [-0.2474,  0.0376, -0.9917, -0.3229, -0.8140, -0.6114, -0.0665,
           0.0286]],

        [[-1.3017, -1.4547,  1.7709, -0.8887,  1.0936,  0.5941, -0.1536,
           1.1183],
         [-0.9009, -1.9717,  0.4046,  0.1534,  0.7292, -0.7345, -0.0698,
          -0.4895],
         [-1.8335,  0.0600,  1.9100, -1.2072,  1.2051,  0.1280, -1.1

In [49]:
weights = F.softmax(weights.masked_fill(tril==0, float('-inf')), dim=-1)

In [50]:
weights

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5611, 0.4389, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5117, 0.4099, 0.0784, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2771, 0.4023, 0.1232, 0.1973, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2833, 0.1798, 0.0129, 0.1831, 0.3408, 0.0000, 0.0000, 0.0000],
         [0.1426, 0.2778, 0.0468, 0.2083, 0.2244, 0.1001, 0.0000, 0.0000],
         [0.0995, 0.0411, 0.1335, 0.4220, 0.0661, 0.0242, 0.2137, 0.0000],
         [0.1331, 0.1771, 0.0633, 0.1235, 0.0756, 0.0925, 0.1595, 0.1755]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.7448, 0.2552, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0200, 0.1331, 0.8468, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1588, 0.1443, 0.5445, 0.1525, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3613, 0.4062, 0.0161, 0.2088, 0.0075, 0.0000, 0.0000, 0.0000],
         [0.2530, 0.042

In [51]:
out = weights@x

In [52]:
out

tensor([[[-0.2287, -0.1237, -0.0114,  ..., -0.8195, -0.7322,  1.7068],
         [ 0.2487,  0.3834,  0.3233,  ..., -0.2623,  0.3069,  0.5857],
         [ 0.3451,  0.3537,  0.3457,  ..., -0.3482,  0.2361,  0.4868],
         ...,
         [ 0.4575,  0.8141,  0.4379,  ..., -0.0488,  0.1515, -0.4681],
         [ 0.4394,  0.5329,  0.2454,  ...,  0.0430, -0.7996, -0.2245],
         [ 0.2497,  0.7764, -0.0251,  ..., -0.1822, -0.0613, -0.5465]],

        [[ 0.3227, -0.5538, -0.3381,  ..., -1.2027, -0.7461, -1.0881],
         [ 0.0694,  0.0439, -0.3741,  ..., -0.8599, -0.4566, -0.6561],
         [-0.1617, -0.2500,  0.8100,  ...,  1.5481, -0.2401, -0.0278],
         ...,
         [ 0.5280, -0.3127,  0.0021,  ..., -0.8125, -0.0221, -0.3066],
         [-0.0226, -0.2833,  0.0485,  ..., -0.2883, -0.0581, -0.5557],
         [-0.0417,  0.2381, -0.0375,  ..., -0.0780, -0.1851, -0.1739]],

        [[-0.8258,  0.0213, -0.5074,  ..., -1.0995, -0.2794,  0.0512],
         [-0.3375,  0.4494, -0.5916,  ..., -0

In [53]:
value = nn.Linear(dim, head_size, bias=False)

In [54]:
v = value(x)

In [55]:
out = weights@v

In [56]:
out

tensor([[[-1.9893e-01,  3.8479e-01, -3.6142e-01,  6.3646e-01, -5.0286e-02,
           8.3531e-01, -5.3619e-01, -1.9481e-01,  3.1110e-01, -5.5768e-01,
           2.1076e-01,  2.7252e-02, -1.1323e-01, -4.5328e-01,  1.8950e-02,
          -2.8733e-01],
         [ 7.9644e-02, -1.8328e-01, -3.9564e-01,  7.2709e-01,  1.7089e-01,
           4.4149e-01, -9.7890e-02, -3.2651e-01, -1.1713e-01, -5.2378e-01,
           3.0402e-01, -1.3787e-02, -1.8326e-01, -3.0585e-01, -2.4682e-01,
          -7.2937e-01],
         [ 1.9335e-02, -2.1036e-01, -3.1194e-01,  6.5323e-01,  1.0102e-01,
           4.6333e-01, -1.2477e-01, -2.5036e-01, -1.7927e-01, -5.7722e-01,
           3.1218e-01,  2.7355e-02, -1.3516e-01, -3.2260e-01, -2.3864e-01,
          -6.4317e-01],
         [ 8.3087e-02, -5.1429e-01, -1.3816e-01,  4.4450e-01,  6.4652e-02,
           4.1198e-01, -1.0456e-01, -1.0758e-01, -3.7490e-01, -5.9400e-01,
           2.4498e-01,  6.7987e-02, -1.2052e-01, -2.3250e-01, -2.7626e-01,
          -6.4838e-01],
    

# train of GPT model 

In [57]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        weight = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        weight = weight.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        weight = F.softmax(weight, dim=-1) # (B, T, T)
        weight = self.dropout(weight)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = weight @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

In [58]:
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

In [59]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

In [63]:
# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

In [64]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [65]:
class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

10.788929 M parameters


In [66]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

## Homework & Practice

In [ ]:
for iter in range(max_iters):
     # every once in a while evaluate the loss on train and val sets
    

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))